/**
 * Event pages: what is on in a country, and the two streams people search for
 * by name — concerts and comedy.
 *
 * These pages exist to be useful next to the calendar, so every listing is tied
 * back to it: a show landing on a public holiday is flagged, because that is
 * what changes transport, opening hours and prices around it.
 */

import config from '../../site.config.mjs';
import { MONTH_SHORT, formatShort, parseISO } from '../dates.mjs';
import { CATEGORIES, categoryByKey, eventStats, groupByMonth } from '../events.mjs';
import { adSlot, esc, layout, url } from '../html.mjs';

const plural = (count, one, many) => `${count.toLocaleString('en')} ${count === 1 ? one : many}`;

const VIEWS = {
  all: {
    slug: 'events',
    heading: (name) => `What's on in ${name}`,
    title: (name) => `What's on in ${name} — concerts, comedy and live events`,
    noun: 'event',
    nounPlural: 'events',
  },
  concerts: {
    slug: 'concerts',
    heading: (name) => `Concerts in ${name}`,
    title: (name) => `Concerts in ${name} — upcoming gigs and tour dates`,
    noun: 'concert',
    nounPlural: 'concerts',
  },
  comedy: {
    slug: 'comedy',
    heading: (name) => `Comedy shows in ${name}`,
    title: (name) => `Comedy shows in ${name} — stand-up and tour dates`,
    noun: 'comedy show',
    nounPlural: 'comedy shows',
  },
};

/** The banner that must appear on any page built with --events-demo. */
function demoBanner() {
  return `<div class="demo-banner" role="note">
    <p><strong>Sample listings.</strong> These acts, venues and dates are invented, generated by
      <code>--events-demo</code> so the layout can be reviewed without an API key. No real event is
      shown on this page, and it is marked <code>noindex</code>. Set
      <code>TICKETMASTER_API_KEY</code> and rebuild for real listings.</p>
  </div>`;
}

/**
 * One month, one table. The date is a row-group heading spanning its listings
 * rather than a repeated column, which is how a printed listings sheet reads —
 * and it keeps the column headers to one per month instead of one per day.
 */
function monthSection(month, countryCode) {
  const groups = month.days
    .map((day) => {
      const rows = day.events
        .map((event, index) => {
          const name = event.url
            ? `<a href="${esc(event.url)}" rel="noopener nofollow" target="_blank">${esc(
                event.name,
              )}</a>`
            : esc(event.name);
          const where = [event.venue, event.city].filter(Boolean).map(esc).join(', ');

          const dateCell =
            index === 0
              ? `<th scope="row" rowspan="${day.events.length}" class="listings__date">
            <span class="listings__day">${esc(day.weekday.slice(0, 3))}</span>
            <span class="listings__num mono">${esc(day.date.slice(8))} ${esc(
              MONTH_SHORT[Number(day.date.slice(5, 7)) - 1],
            )}</span>
            ${
              day.holiday
                ? `<a class="tag tag--national" href="${url.holiday(countryCode, day.date)}">${esc(
                    day.holiday.name,
                  )}</a>`
                : ''
            }
          </th>`
              : '';

          return `<tr>${dateCell}
        <td class="date">${esc(event.time || '—')}</td>
        <td>${name}${
          // Marked on the row itself, not only in the banner: no single line of
          // this table should be readable as a real listing.
          event.demo ? ' <span class="tag tag--sample">not a real listing</span>' : ''
        }${event.genre ? `<br><span class="note mono">${esc(event.genre)}</span>` : ''}</td>
        <td>${where || '<span class="note">venue to be announced</span>'}</td>
      </tr>`;
        })
        .join('');

      return `<tbody class="${day.holiday ? 'is-holiday' : day.weekend ? 'is-weekend' : ''}">${rows}</tbody>`;
    })
    .join('');

  return `<section class="month-block">
    <h3 class="month-block__head">${esc(month.label)} <span class="note mono">${plural(
      month.count,
      'listing',
      'listings',
    )}</span></h3>
    <div class="table-scroll">
      <table class="listings">
        <thead><tr>
          <th scope="col">Date</th><th scope="col">Time</th>
          <th scope="col">What</th><th scope="col">Where</th>
        </tr></thead>
        ${groups}
      </table>
    </div>
  </section>`;
}

/**
 * One country, one view.
 *
 * @param {{country: object, view: 'all'|'concerts'|'comedy', events: Array,
 *          counts: object, currentYear: number, demo: boolean}} input
 */
export function renderCountryEvents({ country, view, events, counts, currentYear, demo }) {
  const shape = VIEWS[view];
  const stats = eventStats(events);
  // On the comedy page every row is "Comedy"; a label that never varies is
  // noise, so drop it there.
  const shown =
    view === 'comedy'
      ? events.map((event) => (event.genre === 'Comedy' ? { ...event, genre: null } : event))
      : events;
  const months = groupByMonth(shown);
  const heading = shape.heading(country.name);

  const range =
    stats.first && stats.last
      ? `${formatShort(parseISO(stats.first.date))} to ${formatShort(parseISO(stats.last.date))}`
      : '';

  const description =
    `${plural(stats.total, shape.noun, shape.nounPlural)} on sale in ${country.name}` +
    `${stats.cities ? ` across ${plural(stats.cities, 'city', 'cities')}` : ''}` +
    `${range ? `, ${range}` : ''}. ` +
    `${
      stats.onHolidays
        ? `${plural(stats.onHolidays, 'date falls', 'dates fall')} on a public holiday.`
        : 'Dates cross-checked against the public holiday calendar.'
    }`;

  const otherViews = Object.entries(VIEWS)
    .filter(([key]) => key !== view && (key === 'all' || counts[key] > 0))
    .map(
      ([key, other]) =>
        `<li><a class="chip" href="${url.countryEvents(country.code, key)}">${esc(
          other.heading(country.name),
        )}${counts[key] ? ` (${counts[key]})` : ''}</a></li>`,
    )
    .join('');

  const body = `
<section class="hero">
  <div class="wrap">
    <p class="eyebrow">${esc(country.flag)} ${esc(country.name)} · next ${
      config.events.windowDays
    } days</p>
    <h1>${esc(heading)}</h1>
    <p class="lede hero__lede">${esc(description)}</p>
    <ul class="chips">${otherViews}</ul>
  </div>
</section>

${demo ? `<div class="wrap">${demoBanner()}</div>` : ''}

<div class="wrap">${adSlot('leaderboard')}</div>

<section class="section">
  <div class="wrap">
    <div class="facts">
      <div class="fact fact--signal">
        <span class="fact__value">${stats.total}</span>
        <span class="fact__label">${esc(shape.nounPlural)} listed</span>
        <p class="fact__note">${esc(range || 'upcoming')}</p>
      </div>
      <div class="fact">
        <span class="fact__value">${stats.cities}</span>
        <span class="fact__label">Cities</span>
        <p class="fact__note">with something on</p>
      </div>
      <div class="fact">
        <span class="fact__value">${stats.onHolidays}</span>
        <span class="fact__label">On a public holiday</span>
        <p class="fact__note">${
          stats.onHolidays ? 'expect altered transport and hours' : 'none clash with a holiday'
        }</p>
      </div>
      <div class="fact">
        <span class="fact__value">${
          stats.first ? esc(formatShort(parseISO(stats.first.date))) : '—'
        }</span>
        <span class="fact__label">Next date</span>
        <p class="fact__note">${stats.first ? esc(stats.first.name) : ''}</p>
      </div>
    </div>
    ${
      stats.topGenres.length > 1
        ? `<p class="note" style="margin-top:1rem">Most listed: ${stats.topGenres
            .map((genre) => `${esc(genre.name)} (${genre.count})`)
            .join(' · ')}</p>`
        : ''
    }
  </div>
</section>

<div class="wrap">${adSlot('inArticle')}</div>

<section class="section">
  <div class="wrap">
    <div class="section__head">
      <h2>Every date</h2>
      <a href="${url.year(country.code, currentYear)}">${currentYear} holiday calendar →</a>
    </div>
    ${
      months.length
        ? months.map((month) => monthSection(month, country.code)).join('')
        : `<p class="note">Nothing listed for ${esc(country.name)} in this window.</p>`
    }
  </div>
</section>

<section class="section">
  <div class="wrap prose">
    <h2>Planning around these dates</h2>
    <ul>
      <li>Dates marked with a holiday tag fall on a public holiday in ${esc(
        country.name,
      )} — public transport often runs a Sunday timetable and many places close early. The tag links
        to that date in the calendar.</li>
      <li><a href="${url.calculator(country.code)}">Count the working days</a> around a trip, with
        weekends and ${esc(country.name)} public holidays removed.</li>
      <li><a href="${url.country(country.code)}">${esc(
        country.name,
      )} holiday calendars</a> for every year we publish.</li>
    </ul>
    <p class="note">${
      demo
        ? 'Sample data — nothing on this page is a real listing.'
        : `Listings from <a href="https://www.ticketmaster.com" rel="noopener">Ticketmaster</a>, fetched when the site was last built and limited to the next ${config.events.windowDays} days. Availability, times and venues change; check the ticket page before travelling. This site sells nothing and takes no booking.`
    }</p>
  </div>
</section>
`;

  // Real listings get event markup; invented ones must never be marked up as
  // though they were real, and must not be indexed.
  const jsonLd =
    !demo && events.length
      ? {
          '@context': 'https://schema.org',
          '@type': 'ItemList',
          name: heading,
          numberOfItems: events.length,
          itemListElement: events.slice(0, 40).map((event, index) => ({
            '@type': 'ListItem',
            position: index + 1,
            item: {
              '@type': 'Event',
              name: event.name,
              startDate: event.time ? `${event.date}T${event.time}` : event.date,
              eventStatus: 'https://schema.org/EventScheduled',
              ...(event.url ? { url: event.url } : {}),
              location: {
                '@type': 'Place',
                name: event.venue || event.city || country.name,
                address: {
                  '@type': 'PostalAddress',
                  addressLocality: event.city || undefined,
                  addressCountry: country.code,
                },
              },
            },
          })),
        }
      : null;

  return layout({
    title: shape.title(country.name),
    description,
    path: url.countryEvents(country.code, view),
    body,
    jsonLd,
    head: demo ? '<meta name="robots" content="noindex">' : '',
    breadcrumbs: [
      { name: "What's on", path: url.events() },
      { name: country.name, path: url.country(country.code) },
      { name: shape.heading(country.name), path: url.countryEvents(country.code, view) },
    ],
  });
}

/** The hub: which countries have listings at all. */
export function renderEventsHub({ countries, demo, today }) {
  const total = countries.reduce((sum, country) => sum + country.counts.all, 0);
  const description =
    `Concerts, comedy and live events in ${plural(countries.length, 'country', 'countries')}, ` +
    `${total.toLocaleString('en')} dates in the next ${config.events.windowDays} days, ` +
    `each cross-checked against that country's public holidays.`;

  const cards = countries
    .map(
      (country) => `<a class="card" href="${url.countryEvents(country.code, 'all')}">
      <span class="card__name">${esc(country.flag)} ${esc(country.name)}</span>
      <span class="card__meta">${country.counts.all} listings · ${country.counts.concerts} concerts · ${
        country.counts.comedy
      } comedy</span>
      <span class="card__meta">${
        country.next ? `Next: ${esc(country.next.name)}, ${esc(formatShort(parseISO(country.next.date)))}` : ''
      }</span>
    </a>`,
    )
    .join('');

  const body = `
<section class="hero">
  <div class="wrap">
    <p class="eyebrow">${today} · next ${config.events.windowDays} days</p>
    <h1>What's on, and when the country is off</h1>
    <p class="lede hero__lede">Concerts, comedy and live events in ${plural(
      countries.length,
      'country',
      'countries',
    )} — with every date checked against that country's public holiday calendar, because a show on a
      public holiday means different transport, different opening hours and different prices.</p>
  </div>
</section>

${demo ? `<div class="wrap">${demoBanner()}</div>` : ''}

<div class="wrap">${adSlot('leaderboard')}</div>

<section class="section">
  <div class="wrap">
    <h2>Countries with listings</h2>
    <div class="grid">${cards}</div>
  </div>
</section>

<div class="wrap">${adSlot('inArticle')}</div>

<section class="section">
  <div class="wrap prose">
    <h2>How this list is built</h2>
    <p>Listings come from the Ticketmaster Discovery API, refreshed on every nightly rebuild and
      limited to the next ${config.events.windowDays} days. Coverage follows that source: it is
      strong in North America, the UK, Ireland, Australia and much of western Europe, and thin or
      absent elsewhere. A country with no listings simply gets no page rather than an empty one.</p>
    <p>Every date is matched against the public holiday calendar for that country, so you can see at
      a glance which shows land on a day the country is off. Ticket links go to the seller; this site
      sells nothing, takes no booking, and earns nothing from a click-through.</p>
    <p><a href="${url.about()}">Method and limits →</a></p>
  </div>
</section>
`;

  return layout({
    title: "What's on — concerts, comedy and live events by country",
    description,
    path: url.events(),
    body,
    head: demo ? '<meta name="robots" content="noindex">' : '',
    breadcrumbs: [{ name: "What's on", path: url.events() }],
  });
}

export { CATEGORIES };
