import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { audit } from '@/lib/session';

/**
 * Where every emailed auth link lands: signup confirmation, password reset and
 * magic links all arrive here with a one-time token, which is exchanged for a
 * session cookie and then discarded from the URL.
 *
 * Supabase sends either a `token_hash` + `type` pair (the current flow) or a
 * `code` (PKCE). Both are handled so a link generated by either template
 * works.
 */
export async function GET(request: NextRequest) {
  const url = new URL(request.url);
  const tokenHash = url.searchParams.get('token_hash');
  const type = url.searchParams.get('type');
  const code = url.searchParams.get('code');
  const rawNext = url.searchParams.get('next');

  // Only same-origin paths, so a crafted link cannot bounce someone off-site
  // carrying a fresh session.
  const next = rawNext && rawNext.startsWith('/') && !rawNext.startsWith('//') ? rawNext : '/dashboard';

  const supabase = await createClient();

  if (tokenHash && type) {
    const { error } = await supabase.auth.verifyOtp({
      type: type as 'signup' | 'recovery' | 'invite' | 'email_change' | 'magiclink',
      token_hash: tokenHash,
    });
    if (!error) {
      await audit(null, { action: 'auth.link_confirmed', detail: { type } });
      return NextResponse.redirect(new URL(next, url.origin));
    }
    return NextResponse.redirect(
      new URL(`/verify?error=${encodeURIComponent(error.message)}`, url.origin)
    );
  }

  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      await audit(null, { action: 'auth.link_confirmed', detail: { type: 'code' } });
      return NextResponse.redirect(new URL(next, url.origin));
    }
    return NextResponse.redirect(
      new URL(`/verify?error=${encodeURIComponent(error.message)}`, url.origin)
    );
  }

  return NextResponse.redirect(new URL('/verify?error=missing', url.origin));
}
