"""Write rules/CHECKLIST.md: every value a person still has to supply.

Derived from the YAML rather than written alongside it, so the checklist
cannot fall out of step with the files it describes. Anything marked
`confirmed` drops off it automatically.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
STATES = ROOT / "rules" / "states"
OUT = ROOT / "rules" / "CHECKLIST.md"


def main() -> None:
    missing: dict[str, list[dict]] = {}
    confirm: dict[str, list[dict]] = {}
    names: dict[str, str] = {}
    instruments: dict[str, str] = {}

    for path in sorted(STATES.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        code = data["state"]
        names[code] = data["name"]
        instruments[code] = data["planning_instrument"]
        for rule in data["rules"]:
            bucket = {"missing": missing, "confirm": confirm}.get(rule["status"])
            if bucket is not None:
                bucket.setdefault(code, []).append(rule)

    total_missing = sum(len(v) for v in missing.values())
    total_confirm = sum(len(v) for v in confirm.values())

    # Which of these stop a plan being drawn at all, rather than leaving one
    # check unanswered. Read from the solver's own definition rather than
    # listed again here, so the two cannot drift apart.
    #
    # Without this the checklist is 152 rows in alphabetical order and says
    # nothing about which matter. Four states cannot draw at all and each is
    # held up by the same five figures; a builder in South Australia reading
    # a flat list of twenty-two has no way to see that.
    import sys
    sys.path.insert(0, str(ROOT / "src"))
    from codraft.codes.states import missing_essential   # noqa: E402

    blocked: dict[str, list[str]] = {}
    for code in sorted(missing):
        stops = sorted(missing_essential(f"AU-{code.upper()}"))
        if stops:
            blocked[code] = stops

    lines = [
        "# Rule values to supply",
        "",
        "Generated by `tools/build_checklist.py` from `rules/states/*.yaml`.",
        "Regenerate after editing any of those files.",
        "",
        "**Nothing in this repository has guessed any of these figures.** Where a",
        "value is present it came from a rule pack that cites its own source, and",
        "it is listed below under *confirm* rather than treated as settled. Where",
        "no value is present it says `TODO` and is listed under *missing*.",
        "",
        f"- **{total_missing}** values missing entirely",
        f"- **{total_confirm}** values present from an existing pack, needing"
        " verification against the current edition",
        "",
        "Not all of them weigh the same. A few STOP A PLAN BEING DRAWN for a",
        "location: with no setbacks and no coverage cap there is no envelope to",
        "put a house in, so `codraft plan \"... in Adelaide\"` refuses and names",
        "them rather than drawing a house on a lot it cannot bound. (A caller",
        "that supplies its own setbacks still gets a drawing; what it does not",
        "get is that state\u2019s controls applied to it.) The rest leave a single",
        "check unanswered, which the report reports as `unchecked` rather than",
        "passing it.",
        "",]
    if blocked:
        lines += [
            f"## Start here — {sum(len(v) for v in blocked.values())} values"
            f" across {len(blocked)} states stop a plan being drawn",
            "",
            "| state | figures needed before anything can be drawn |",
            "|---|---|",
        ]
        for code, stops in blocked.items():
            lines.append(
                f"| {names[code]} (`{code}`) | "
                + ", ".join(f"`{k}`" for k in stops) + " |"
            )
        lines += [
            "",
            "Every other state in this file plans for a location today.",
            "Supplying these figures for one of the states above is the",
            "difference between codraft refusing there and codraft working.",
            "",
        ]
    lines += [
        "Set `last_checked` to the date you checked it and `status: confirmed`",
        "once a figure has been read off the instrument itself.",
        "",
        "---",
        "",
        "## Missing — no figure exists, and none has been invented",
        "",
    ]

    for code in sorted(missing):
        lines.append(f"### {names[code]} (`{code}`)")
        lines.append("")
        lines.append(f"Instrument: {instruments[code]}")
        lines.append("")
        lines.append("| id | what it is | unit | where to look |")
        lines.append("|---|---|---|---|")
        for rule in missing[code]:
            source = rule["source"] if rule["source"] != "TODO" else "—"
            lines.append(
                f"| `{rule['id']}` | {rule['description']} | {rule['unit']} "
                f"| {source} |"
            )
        lines.append("")

    if confirm:
        lines += [
            "---",
            "",
            "## Confirm — a figure is present and cites a source",
            "",
            "These came from codraft's rule packs. They are not guesses, but no",
            "person has checked them against the current edition of the",
            "instrument, and editions change.",
            "",
        ]
        for code in sorted(confirm):
            lines.append(f"### {names[code]} (`{code}`)")
            lines.append("")
            lines.append("| id | value | source |")
            lines.append("|---|---|---|")
            for rule in confirm[code]:
                value = rule["value"]
                if isinstance(value, dict):
                    value = ", ".join(f"{k} {v}" for k, v in value.items())
                lines.append(f"| `{rule['id']}` | {value} | {rule['source']} |")
            lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {total_missing} missing, "
          f"{total_confirm} to confirm")


if __name__ == "__main__":
    main()
