"""Write rules/CHECKLIST.md: every value a person still has to supply.

Derived from the YAML rather than written alongside it, so the checklist
cannot fall out of step with the files it describes. Anything marked
`confirmed` drops off it automatically.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
STATES = ROOT / "rules" / "states"
OUT = ROOT / "rules" / "CHECKLIST.md"


def main() -> None:
    missing: dict[str, list[dict]] = {}
    confirm: dict[str, list[dict]] = {}
    names: dict[str, str] = {}
    instruments: dict[str, str] = {}

    for path in sorted(STATES.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        code = data["state"]
        names[code] = data["name"]
        instruments[code] = data["planning_instrument"]
        for rule in data["rules"]:
            bucket = {"missing": missing, "confirm": confirm}.get(rule["status"])
            if bucket is not None:
                bucket.setdefault(code, []).append(rule)

    total_missing = sum(len(v) for v in missing.values())
    total_confirm = sum(len(v) for v in confirm.values())

    lines = [
        "# Rule values to supply",
        "",
        "Generated by `tools/build_checklist.py` from `rules/states/*.yaml`.",
        "Regenerate after editing any of those files.",
        "",
        "**Nothing in this repository has guessed any of these figures.** Where a",
        "value is present it came from a rule pack that cites its own source, and",
        "it is listed below under *confirm* rather than treated as settled. Where",
        "no value is present it says `TODO` and is listed under *missing*.",
        "",
        f"- **{total_missing}** values missing entirely",
        f"- **{total_confirm}** values present from an existing pack, needing"
        " verification against the current edition",
        "",
        "Set `last_checked` to the date you checked it and `status: confirmed`",
        "once a figure has been read off the instrument itself.",
        "",
        "---",
        "",
        "## Missing — no figure exists, and none has been invented",
        "",
    ]

    for code in sorted(missing):
        lines.append(f"### {names[code]} (`{code}`)")
        lines.append("")
        lines.append(f"Instrument: {instruments[code]}")
        lines.append("")
        lines.append("| id | what it is | unit | where to look |")
        lines.append("|---|---|---|---|")
        for rule in missing[code]:
            source = rule["source"] if rule["source"] != "TODO" else "—"
            lines.append(
                f"| `{rule['id']}` | {rule['description']} | {rule['unit']} "
                f"| {source} |"
            )
        lines.append("")

    if confirm:
        lines += [
            "---",
            "",
            "## Confirm — a figure is present and cites a source",
            "",
            "These came from codraft's rule packs. They are not guesses, but no",
            "person has checked them against the current edition of the",
            "instrument, and editions change.",
            "",
        ]
        for code in sorted(confirm):
            lines.append(f"### {names[code]} (`{code}`)")
            lines.append("")
            lines.append("| id | value | source |")
            lines.append("|---|---|---|")
            for rule in confirm[code]:
                value = rule["value"]
                if isinstance(value, dict):
                    value = ", ".join(f"{k} {v}" for k, v in value.items())
                lines.append(f"| `{rule['id']}` | {value} | {rule['source']} |")
            lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {total_missing} missing, "
          f"{total_confirm} to confirm")


if __name__ == "__main__":
    main()
